### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#1311]
I was doing some fairly heavy (as in, a lot of them in a short space of time) HTTP request calls to an HTTP input node in another tab, and it became unresponsive and the Mac fan started up. When I eventually ctrl-C'd it, I got:
```
<--- Last few GCs --->

33246455 ms: Scavenge 1396.0 (1452.0) -> 1396.0 (1452.0) MB, 0.2 / 0 ms [allocation failure].
33246455 ms: Scavenge 1396.0 (1452.0) -> 1396.0 (1452.0) MB, 0.1 / 0 ms [allocation failure].
33246456 ms: Scavenge 1396.0 (1452.0) -> 1396.0 (1452.0) MB, 0.1 / 0 ms [allocation failure].
33246537 ms: Mark-sweep 1396.0 (1452.0) -> 1396.0 (1452.0) MB, 81.0 / 0 ms [last resort gc].
33246612 ms: Mark-sweep 1396.0 (1452.0) -> 1396.0 (1452.0) MB, 75.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x35e2eddb4629 <JS Object>
    1: Join(aka Join) [native array.js:154] [pc=0x3ef70554b118] (this=0x35e2edd041b9 <undefined>,o=0x240a719cd149 <JS Array[10]>,v=10,C=0x3d224fbae71 <String[60]\: ,\n                                                          >,B=0x35e2eddb3e71 <JS Function ConvertToString (SharedFunctionInfo 0x35e2edd51c21)>)
    2: InnerArrayJoin(aka InnerArrayJoin) [native array.js:331] [pc=0x3ef705549f8a] (t...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6
```

**Comment by knolleary** [comment]
You're going to have to do some more leg work on this. Is this a new behaviour or a result of changing what you're testing?

What are your flows doing? We know of users running flows at 400 reqs/second without issue, so there isn't an inherent issue with the HTTP nodes.

**Comment by andysc** [comment]
it's the same flow that used to work, now running on 0.17.
Trying to narrow it down. It just did it again, but OOMd of its own accord without the ctrl-C.
I think it ignored my ctrl-C and just popped when the memory filled up

**Comment by andysc** [comment]
OK - it's something to do with inspection of the msg coming out of the HTTP-input node.
With the following flow, if you have the debug after the HTTP disabled, it works fine. If you enable it, it takes "forever" and eats loads of memory.

This works fine (with debug of complete message enabled) on 0.16, btw.

```
[{"id":"cafeb2ca.9fff9","type":"inject","z":"fd656f8a.f6f2a8","name":"","topic":"","payload":"100","payloadType":"num","repeat":"","crontab":"","once":false,"x":130,"y":160,"wires":[["33e43a0f.805336"]]},{"id":"83b1d30c.92e5a","type":"debug","z":"fd656f8a.f6f2a8","name":"","active":true,"console":"false","complete":"payload","x":630,"y":220,"wires":[]},{"id":"33e43a0f.805336","type":"function","z":"fd656f8a.f6f2a8","name":"list","func":"var output = [];\nfor (var i=0; i<msg.payload; i++)\n    output.push({payload: i+1});\nreturn [output];","outputs":1,"noerr":0,"x":260,"y":220,"wires":[["c1ce5e5d.d08cd"]]},{"id":"27646606.f5f482","type":"http in","z":"fd656f8a.f6f2a8","name":"","url":"/fred","method":"get","upload":false,"swaggerDoc":"","x":100,"y":360,"wires":[["ccff1e31.1c03a","6de7ebde.3145a4"]]},{"id":"2b10437f.d7d214","type":"http response","z":"fd656f8a.f6f2a8","name":"","statusCode":"","headers":{},"x":430,"y":360,"wires":[]},{"id":"ccff1e31.1c03a","type":"template","z":"fd656f8a.f6f2a8","name":"","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"Hello World ({{payload.number}})","output":"str","x":270,"y":360,"wires":[["2b10437f.d7d214"]]},{"id":"6de7ebde.3145a4","type":"debug","z":"fd656f8a.f6f2a8","name":"","active":true,"console":"false","complete":"true","x":270,"y":300,"wires":[]},{"id":"c1ce5e5d.d08cd","type":"http request","z":"fd656f8a.f6f2a8","name":"call /fred","method":"GET","ret":"txt","url":"http://localhost:1880/fred?number={{payload}}","tls":"","x":440,"y":220,"wires":[["83b1d30c.92e5a"]]}]
```

**Comment by andysc** [comment]
Oh, and you get 
`RangeError: Invalid string length`
errors coming out of the debug node.

**Comment by andysc** [comment]
that's not the whole story, as I removed that node from my more complicated flow (which accesses various parts of msg.req., and it still has problems)

**Comment by knolleary** [comment]
Thanks for the test case - always helps. Node.js is single threaded. It relies on an application making good use of the event loop to ensure the various 'concurrent' activities get fair time.

Currently, the Debug node writes to the connected WebSocket synchronously to the message being passed to it. When debugging the complete msg object of an http request, there's a lot of data and doing it synchronously to the originating HTTP Request got things jamming up. Not entirely clear why it was causing such slow down - but the slow down caused a build-up of events and eventually it goes pop.

The fix I've just pushed means the write to the websocket is done asynchronously to the originating request. That simple change allows the node.js event scheduling to do the right thing. You test case now completes in little more than a second.

Note: the Debug sidebar only shows the 100 most recent messages. Your test case sends 100 messages and each causes two debug messages to be sent. The nature of the change means the 100 messages from the HTTP In flow appear first followed by the messages from the Debug node at the end of triggering flow... but because of the 100 message limit you'll only see that second 100 set. I got caught out by that as it left me wondering where the first 100 had gone. But if you reduce your inject to 50 you'll see the lot of them.

**Comment by andysc** [comment]
marvellous - thanks Nick!

**Comment by andysc** [comment]
re-opening this, as I'm still seeing a very closely related problem.

Insert a 1 sec delay node into the HTTP listener flow of my test case (e.g. before the HTTP-out node), and reduce the messages in the inject node to 15, and enable the debug complete msg node.
When you activate this flow, it goes to 100% CPU and uses about 2gig of RAM before any results came out. 
Sometimes it actually completes after a few minutes, other times it crashes node-red with:
```
3 Jul 13:21:29 - [red] Uncaught Exception:
3 Jul 13:21:29 - RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at stringify (/usr/local/lib/node_modules/node-red/node_modules/json-stringify-safe/stringify.js:5:15)
    at sendDebug (/usr/local/lib/node_modules/node-red/nodes/core/core/58-debug.js:128:31)
    at null._onTimeout (/usr/local/lib/node_modules/node-red/nodes/core/core/58-debug.js:33:25)
    at Timer.listOnTimeout (timers.js:92:15)
Andys-MacBook-Pro:.node-red andysc$ node-red http_test.json 
3 Jul 13:21:50 - [info] 
```
This is 0.17.2

**Comment by knolleary** [comment]
FYI, a quick search reveals that `RangeError: Invalid string length` is how the underlying v8 engine will sometimes report an OutOfMemory error when hit within `Object.stringify`:: https://github.com/nodejs/node-v0.x-archive/issues/14170

**Comment by knolleary** [comment]
Some interesting discoveries.

I added a bit of debug to the Debug node to print out the length of the JSON string it is sending to the browser for each message.

If I send 5 requests using your flow (with only the second debug node enabled), I get the following sizes:

    5355131
    5529811
    5711786
    5901066
    6097646

Yes, that's averaging 6Mb of data. Ouch.

Now, I up it to 6 requests (after a clean restart):

    9143149
    9445064
    9754284
    10070794
    10394609
    788440

This time, 10Mb of data... for each message. Double ouch.

Looking at the HTTP Request object, there's a lot of data in there, that, frankly we don't need to expose to Debug. The challenge is finding a way to filter it efficiently.

Cutting the story short, we now skip any object that is of type ServerResponse or Socket. These are internal objects that we've never guaranteed the presence of. If we ever encounter one being passed to Debug, we now replace it with the text `[internal]`. There _might_ be legitimate reasons to see these objects in Debug, but to be honest, I'd rather sort out this performance issue now a d have that discussion when someone finds they can't see them later.

With this fix in place, the size output is now:

    3064
    3064
    3064
    3065
    3064
    3065

Yup, from 10Mb all the way down to 3k. That'll do nicely.

**Comment by andysc** [comment]
Lovely - good sleuthing, Nick! How did you narrow down to ServerResponse and Socket? 
Hmm - actually, now you mention it, that was where I was finding weird stuff like copies of the last-deployed flow and stuff.
I also suspect there might be some circular references in there too.
Anyway, thank you again for a sterling effort!
